<?php

declare(strict_types=1);

require_once __DIR__ . '/config.php';
require_once __DIR__ . '/db.php';

function installRequirements(): array
{
    $uploadDir = dirname(__DIR__) . '/access/img/uploads';

    return [
        ['label' => 'PHP 8.1+', 'ok' => version_compare(PHP_VERSION, '8.1.0', '>=')],
        ['label' => 'PDO extension', 'ok' => extension_loaded('pdo')],
        ['label' => 'PDO MySQL extension', 'ok' => extension_loaded('pdo_mysql')],
        ['label' => '.env writable', 'ok' => is_writable(dirname(__DIR__))],
        ['label' => 'Upload directory writable', 'ok' => is_dir($uploadDir) ? is_writable($uploadDir) : is_writable(dirname($uploadDir))],
    ];
}

function installRequirementsPassed(): bool
{
    foreach (installRequirements() as $requirement) {
        if (empty($requirement['ok'])) {
            return false;
        }
    }

    return true;
}

function isInstalled(): bool
{
    $connection = db();
    if (!$connection) {
        return false;
    }

    try {
        $stmt = $connection->prepare('SELECT setting_value FROM settings WHERE setting_key = :key LIMIT 1');
        $stmt->execute([':key' => 'app_installed']);
        $value = $stmt->fetchColumn();

        return $value === '1';
    } catch (Throwable $exception) {
        return false;
    }
}

function upsertSettingWithConnection(PDO $connection, string $key, string $value): bool
{
    $stmt = $connection->prepare('INSERT INTO settings (setting_key, setting_value) VALUES (:k, :v) ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value)');
    return $stmt->execute([':k' => $key, ':v' => $value]);
}

function upsertSetting(string $key, string $value): bool
{
    $connection = db();
    if (!$connection) {
        return false;
    }

    try {
        return upsertSettingWithConnection($connection, $key, $value);
    } catch (Throwable $exception) {
        return false;
    }
}

function normalizeIpList(string $rawList): array
{
    $items = preg_split('/[\r\n,]+/', $rawList) ?: [];
    $normalized = [];

    foreach ($items as $item) {
        $candidate = trim($item);
        if ($candidate === '') {
            continue;
        }

        if (strpos($candidate, '/') !== false) {
            [$ip, $mask] = array_pad(explode('/', $candidate, 2), 2, '');
            if (filter_var($ip, FILTER_VALIDATE_IP) && ctype_digit($mask)) {
                $normalized[] = $ip . '/' . $mask;
            }
            continue;
        }

        if (filter_var($candidate, FILTER_VALIDATE_IP)) {
            $normalized[] = $candidate;
        }
    }

    return array_values(array_unique($normalized));
}

function installerConnect(array $dbConfig): PDO
{
    $dsn = sprintf(
        'mysql:host=%s;port=%s;dbname=%s;charset=utf8mb4',
        $dbConfig['host'],
        $dbConfig['port'],
        $dbConfig['name']
    );

    return new PDO($dsn, $dbConfig['user'], $dbConfig['pass'], [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    ]);
}

function importSchema(PDO $connection): void
{
    $schemaPath = dirname(__DIR__) . '/database/schema.sql';
    $sql = file_get_contents($schemaPath);
    if (!is_string($sql) || trim($sql) === '') {
        throw new RuntimeException('Schema file missing or empty.');
    }

    $connection->exec($sql);
}

function writeEnvConfig(array $dbConfig, string $baseUrl, string $whitelist): void
{
    $envPath = dirname(__DIR__) . '/.env';
    $data = [
        'DB_HOST' => $dbConfig['host'],
        'DB_PORT' => $dbConfig['port'],
        'DB_NAME' => $dbConfig['name'],
        'DB_USER' => $dbConfig['user'],
        'DB_PASS' => $dbConfig['pass'],
        'BASE_URL' => $baseUrl,
        'ADMIN_IP_WHITELIST' => $whitelist,
    ];

    $lines = ["# Auto-generated by installer", ''];
    foreach ($data as $key => $value) {
        $escaped = str_replace("\n", '', (string)$value);
        $lines[] = $key . '="' . str_replace('"', '\\"', $escaped) . '"';
    }

    $content = implode(PHP_EOL, $lines) . PHP_EOL;
    if (file_put_contents($envPath, $content) === false) {
        throw new RuntimeException('Unable to write .env file. Check file permissions.');
    }
}

function upsertAdmin(PDO $connection, string $name, string $email, string $password): void
{
    $hash = password_hash($password, PASSWORD_DEFAULT);
    if ($hash === false) {
        throw new RuntimeException('Failed to hash admin password.');
    }

    $stmt = $connection->prepare('INSERT INTO admins (name, email, password_hash) VALUES (:name, :email, :hash) ON DUPLICATE KEY UPDATE name = VALUES(name), password_hash = VALUES(password_hash)');
    $stmt->execute([':name' => $name, ':email' => $email, ':hash' => $hash]);
}
